MODEL:
  META_ARCHITECTURE: "GoMatching"  # note
  FREEZE_TYPE: "ExceptROIheads"
  PIXEL_MEAN: [ 123.675, 116.280, 103.530 ]
  PIXEL_STD: [ 58.395, 57.120, 57.375 ]
  BACKBONE:
    NAME: "build_resnet_backbone"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    OUT_FEATURES: [ "res3", "res4", "res5" ]
  WEIGHTS: 'pretrained_models/deepsolo_ic15.pth'  # note
  TRANSFORMER:
    ENABLED: True
    NUM_FEATURE_LEVELS: 4
    TEMPERATURE: 10000
    ENC_LAYERS: 6
    DEC_LAYERS: 6
    DIM_FEEDFORWARD: 1024
    HIDDEN_DIM: 256
    DROPOUT: 0.0
    NHEADS: 8
    NUM_QUERIES: 100
    ENC_N_POINTS: 4
    DEC_N_POINTS: 4
    NUM_POINTS: 25
    INFERENCE_TH_TEST: 0.4
    LOSS:
      POINT_CLASS_WEIGHT: 1.0
      POINT_COORD_WEIGHT: 1.0
      POINT_TEXT_WEIGHT: 0.5
      BOUNDARY_WEIGHT: 0.5
  ROI_HEADS:
    NAME: LSTMatcher
    PROPOSAL_APPEND_GT: False
    NUM_CLASSES: 1
  ASSO_ON: True
  ASSO_HEAD:
    NEG_UNMATCHED: True
    ASSO_THRESH: 0.3
    ASSO_WEIGHT: 0.5
    ASSO_WEIGHT_LOCAL: 0.5
    NUM_WEIGHT_LAYERS: 0
    NUM_FC: 2
    NO_POS_EMB: True
SOLVER:
  USE_CUSTOM_SOLVER: True
  MAX_ITER: 30000
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.00005
  OPTIMIZER: ADAMW
  IMS_PER_BATCH: 1
  CHECKPOINT_PERIOD: 5000
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.1
    NORM_TYPE: 2.0
  BACKBONE_MULTIPLIER: 0.1
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: EfficientDetResizeCrop
  TRAIN_SIZE: 1280
  NOT_CLAMP_BOX: True
  TEST_INPUT_TYPE: square
  MIN_SIZE_TEST: 1440 
  MAX_SIZE_TEST: 4000 
  VIDEO:
    TRAIN_LEN: 6
    TEST_LEN: 6
VIDEO_INPUT: True
VIDEO_TEST:
  MAX_CENTER_DIST: 1.0
  OVERLAP_THRESH: 0.2
  DECAY_TIME: 0.9
  WITH_IOU: True
  NOT_MULT_THRESH: True
  MIN_TRACK_LEN: 5
DATASETS:
  TRAIN: ("icdar15_train",)
  TEST: ("icdar15_train",)
FIND_UNUSED_PARAM: True
DATALOADER:
  SAMPLER_TRAIN: "TrainingSampler"
OUTPUT_DIR: "./trained_models/ICDAR15/"  # note